# Generated by Django 2.1.5 on 2019-01-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_leaf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('question_from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_from', to='questionnaire.QuestionAnswer')),
                ('question_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to', to='questionnaire.QuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='')),
                ('status', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='historyquestionanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionnaire.QuestionAnswer'),
        ),
    ]
